### ISSUE TITLE
Is snapshotstokeeponsource broken?

### ISSUE THREAD

**Issue by tristan-k** [jollyjinx/ZFS-TimeMachine#19]
I'm running Mac OS X 10.11.0, perl v5.23.4 with [plenv](https://github.com/tokuhirom/plenv) and OpenZFS 1.4.5.  For some reason snapshotstokeeponsource is not respected. 

```
 $ sudo ./zfstimemachinebackup.perl  --sourcedataset=ZFS_HOME/tristank --destinationdataset=ZFS_BACKUP/tristank --snapshotstokeeponsource=1 --createsnapshotonsource --recursive --verbose
```

See the verbose output [here](https://0b.tristank.de/?4149fc21c2b69581#iE4EdoBMoOpqDGzDrPEcxlY6Stc6qM52GPxm7SUdhdI=).

**Comment by jollyjinx** [comment]
the s is missing: snapshotStokeeponsource
