### ISSUE TITLE
$: command not found

### ISSUE THREAD

**Issue by jbruggem** [jollyjinx/ZFS-TimeMachine#22]
This might not be an issue with ZFS-TimeMachine, but in case it is I'm starting my quest for a solution here :).

When I run: 

``` bash
sudo perl zfstimemachinebackup.perl  --sourcedataset=zfsdata/home --destinationdataset=zfsexternal/backup --snapshotstokeeponsource=10 --createsnapshotonsource --recursive --debug
```

I get this: 

``` bash
$: command not found
```

Context:
- Ubuntu 16.04 LTS (xenial)
- perl is installed and works

What should I look for to find a solution ?

**Comment by jollyjinx** [comment]
Weird, I suspect that zfs or other commands are not in the path ?  I'm usually using zsh instead of bash - so maybe that is a problem maybe.

**Comment by jbruggem** [comment]
thanks for your reply!

Indeed, using bash is the issue, it runs fine with zsh. I'll see if I can find out more.

**Comment by jbruggem** [comment]
Oh, I forgot to follow up as promised. In bash, the following works : 
```bash
sudo perl -I $PWD ./zfstimemachinebackup.perl [...]
```
