### ISSUE TITLE
JNX::ZFS

### ISSUE THREAD

**Issue by edfriedmangvs** [jollyjinx/ZFS-TimeMachine#26]
When trying to run zfstimemachinebackup.perl, I received an error message that said: "Can't locate JNX/ZFS.pm in @INC". Is there some way to install JNX::ZFS?

**Comment by jollyjinx** [comment]
the required files in JNX directory are in this repository. either start the script from the repository directory or add the JNX to the include path.

**Comment by jollyjinx** [comment]
one optimisation would be to have the include path always use the path where the program was started as additional include path. feel free to add that.
