### ISSUE TITLE
automount of backup zfs filesystem is dangerous

### ISSUE THREAD

**Issue by Fyr42** [jollyjinx/ZFS-TimeMachine#27]
backup snapshot are automounted on /var /usr and so on. Application are confused. New data are written on the backup and not the original /usr /var and so on.

**Comment by jollyjinx** [comment]
well, that depends on how and where you have setup mount points. If you disable mounting the top level or mount them somewhere else it's not a problem.

**Comment by Fyr42** [comment]
mounting point is inherited via send/received. Specialy during the first initial backup.
